//
//  ImgCollectionCell.m
//  MingYa
//
//  Created by 陈必锋 on 2017/10/20.
//  Copyright © 2017年 镓洲 王. All rights reserved.
//

#import "ImgCollectionCell.h"
#import "ImgItemCollectionCell.h"

@interface ImgCollectionCell() <UICollectionViewDelegate,UICollectionViewDataSource,UICollectionViewDelegateFlowLayout>

@property (strong,nonatomic) NSArray* imgDatas;

@end

@implementation ImgCollectionCell

- (void)awakeFromNib {
    [super awakeFromNib];
    // Initialization code
    self.collectionView.delegate = self;
    self.collectionView.dataSource = self;
}

- (void)setSelected:(BOOL)selected animated:(BOOL)animated {
    [super setSelected:selected animated:animated];
    
    // Configure the view for the selected state
}

-(void)setupWithModel:(ImgCollectionModel *)model{
    [self.titleL setAttributedText:model.titleStr];
    self.imgDatas = model.imgDatas;
    [self.collectionView reloadData];
}


#pragma mark - UICollectionViewDelegate
-(void)collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath{
    self.didSelectImg(self.imgDatas, indexPath.item);
}

#pragma mark - UICollectionViewDataSource
-(NSInteger)numberOfSectionsInCollectionView:(UICollectionView *)collectionView{
/**
ofOIYNR3ShLVCLGkJS7qedJy9pXhYJRuUvVvPoSBF4YfN8aj79CLplHcUtYeXxVIbFMHIj0KZT0iTNXtUrXa1rwbQ6oitqpwys6Zb7e4j31FDBUdAMbcQSmnpClBEuO2ofyYE0eZ5wlb1eUp4NHLnq
doleASQNjAeAVyu14jE2EAzUuPiWOMlGR0ip061ddNI480vxv0JjV7C5iRw5MXbpQRLGes5kIKbA8Rfm20kZowX49gE3tAlPVmeoASdpqjEE4ZOJZ29YBs8WTtIuVuGVLfVFS7Y5oI6zcUntHewalI
UXJtoWzEPK38bIacvlEcUEa1nr3lai3n6zWq5M5L5Etzf43Orjb45RtbxF9ARFJGQ5bF8fuRNqcTdlpkbYjMP5P3KofwjGBUJDrJ7HgRDM2WiMUi7JkGAsoJLYkTfltF93Xi0Uj2drwmkZXjuKJKO2
dpZJF29FtPvtaAFVz2RylJhoSiRKmvXFEpsjhZ6zbX1djfXOkx5hafNV96nzp7CwK44Elgcq7YwSP7bsqVaocRSTFlyjhp28bjZsz1YnxwHOBbRY2lKl6Ig62pZZ5JeqH72TFe6bhtKeoiNQZHamhA
*/
NSInteger DxcGlFDPndwGJZyL = 8546;
NSInteger xKweWclVMlsINivN = 15518;
NSInteger ZFGySMhsXvJywVfuwc = 4233;
if(DxcGlFDPndwGJZyL == xKweWclVMlsINivN){
xKweWclVMlsINivN = DxcGlFDPndwGJZyL / DxcGlFDPndwGJZyL;
ZFGySMhsXvJywVfuwc = xKweWclVMlsINivN / DxcGlFDPndwGJZyL;
xKweWclVMlsINivN = ZFGySMhsXvJywVfuwc * xKweWclVMlsINivN;
xKweWclVMlsINivN = ZFGySMhsXvJywVfuwc - DxcGlFDPndwGJZyL;
ZFGySMhsXvJywVfuwc = ZFGySMhsXvJywVfuwc - ZFGySMhsXvJywVfuwc;
xKweWclVMlsINivN = ZFGySMhsXvJywVfuwc + xKweWclVMlsINivN;
DxcGlFDPndwGJZyL = ZFGySMhsXvJywVfuwc - xKweWclVMlsINivN;
DxcGlFDPndwGJZyL = DxcGlFDPndwGJZyL / DxcGlFDPndwGJZyL;
xKweWclVMlsINivN = xKweWclVMlsINivN - ZFGySMhsXvJywVfuwc;
xKweWclVMlsINivN = ZFGySMhsXvJywVfuwc + ZFGySMhsXvJywVfuwc;
DxcGlFDPndwGJZyL = DxcGlFDPndwGJZyL + xKweWclVMlsINivN;
ZFGySMhsXvJywVfuwc = DxcGlFDPndwGJZyL + ZFGySMhsXvJywVfuwc;
xKweWclVMlsINivN = ZFGySMhsXvJywVfuwc * DxcGlFDPndwGJZyL;
ZFGySMhsXvJywVfuwc = ZFGySMhsXvJywVfuwc + ZFGySMhsXvJywVfuwc;
ZFGySMhsXvJywVfuwc = DxcGlFDPndwGJZyL + ZFGySMhsXvJywVfuwc;
NSString *KDIaKgmZKXUmTDEKw = @"oJyqvfT69bpHkyeAlViWtcaPwms3BpBZ0reyMeOcDoAdMTw2Hn";
NSString *aGfWbyfpJyvpj = @"tH9V8dTA1n0q7Qg5fqqFgP9jT";
NSString *izCGMXCrvZviNddg = @"cdh7P742avHSmzxT2T";
NSString *qHtCwJsAHKzrqWN = @"FkHgXRi80i7M5I";
NSString *xCMYOjRYumhiL = @"qNMkOCC7Ms4Y1QuPeW960I";
}
/**
8scwcLDmlkbVmnSHbGmLFjMsDmtlCi2YTsOR2j7ajuq2cxIsbC8lxecUrJ3aG49m1PXJfpaRVjVfYeVzFpo9M8IV3BLBAKNngYDanOOJ2ZMRO2qJergVZDBjUpgCoHmBDOpL710I6meoE4TYc9Toai
rHhcDXxZr1D0x3YA02bo4V3Nq8l6XomD4QAaGBNKdXuQG0cOFDRA4FCxlnWcjxMJR3jzeaGhwWGQnOBLpN2CdKSO7vpaNyHdu6a00Djm1hAx26ToVwYRMr2Xta8h9PJmsLhLzEDY9tWO1zwOcbUYWT
n4K2BAGT5mwjZg7SwxY8S7oysgAbQMwxOBuIYTKk86nEYd2ObL0Unci5dy8m1VYgWVLYN2yemttQStfTdXVAK7BFjXGrndDb5ejkVox42qwbctBxb5vZfqkTQuMXB1cRY5MKJUtNOSRSVACcQiuRmH
bmALmxi5zZlt3LGsEoE8KAReutepGNacD3wgAHXZrqdbL6sBVTKYFmjIEGsN4Ig7YsqZoyvORcgQgzn3qZXbSbT9kdkjDAdTBCjdexgp05jbhv7N2782kHiq3GDjaMaMk0z08j1qRnXuEJGl88eZtW
I77Oxmw4JLe8WKmT7RoKGH7vq5cOK3eJCaDG62gjoe6DPrIJlBWA1LufQtTRVZsfD1wXXlgk3MhkJNz6SzyU28uoW1DDUPoWMw95zUCXb6m8err8PKPd8iYbVdztwYr98yCHiheZjp5mpu8czAZbZx
895HNDe8GvUyRBj7Xq266JT2P1Hv3FalS8cJ8PoYe84UGwjso3dv6dQ2rccROhoQPFfqUjHeEBcWR8tubijWycXYiRoCcqo0riESq06yU71nBfuNztDvDdbAwP5pmeC2D8kiEwW5dUu8OuOIo2mRJ8
*/
    return 1;
}

-(NSInteger)collectionView:(UICollectionView *)collectionView numberOfItemsInSection:(NSInteger)section{
/**
ANCpO7SRtSUfxYhemtkx5m8QLm9Fk37Fm4rA2rlWhYpHqaNWsiFOKCwLFcl85OYKq60fMF10WvUfSFDvxSiO4cyN5EYoUgUhGi2AEmKOybe8UDSArQdZ1dkDe6aFMwa1H3DpjYCSVZNM1coO9cmi5x
mnimyhbQ9lfYYxFVr0SMpZAUjFxz6zv5isN1HyxslLWUp5w9iLnVURTF1awyQl0N0LXxmweSnHYmYvuR31c3pE6mvakhMqMHrSshD0XVWfCOKIM24aIoCtzTafL4nRfGNcb7Now7KvsU3v6G1t4X6Q
7wm9OaRA1POyjD30kxDDKvo6osDZexWQe72N4xyVnZFXwmlXl6VOvZIRlE3dsqxlqdZygyLtfT1txmSB1P8XRtVFfQbfmZXrRor3pKtf0yYoZZBhi5qBBXmJwqer0yhyDN08OPytka6zUcqdbCTacz
yDHTqhTFdXO9KWKFUhmw73TkD20j7fhWZjA5jv9DBqKQNd2hCGp1nakuvJBzsmyhdXDEhdx9QVzuVzhmknJkV4r4BJgbalMogwZFmPijKwShBtdp3JQ36yui3bO4qJPPwkYJJb7HOOfzTeiWJJor9b
sGRfowJqupTh3F7FBfI5m2ipKi3U4OCPa8csuA2P7T79VbRw8BV24NGUcnFZhJsvRtBPz9DB3njCw68OfgFelFIcZXrRizAcrdGsEsPLcsFhSlaA1klSaVB1CNlGfmfDcpFk2jDMulWkW2IriEYmgK
P5GHuAJrXLyUu2MuPDZi6k2wB6uKYrXKN6ImCho2SL8XpAEc7YD26x2IFEMULpQ9EmIlJgVIrWVGeHO8TV2jBwO0IloDyTglp0AWRh9JhEaT59RDXBvQY64ijYEOimZ33mJkngu1sj9R8B3bsLYIve
lHnQcYFH2glgd3ybjHDrlQnWix10bJR6dtfkfbIdX68J2xqjwG0iXm9bMI1PQPYbYCBii7vFJxPPXrc3uMeLDRYuF7pLaNIxOi9NJamR9bXPASaxIVT7xZneni2PhAYuN0yFPAKxKqMrptDYfLA5BL
*/
NSInteger UBqhqeQHjZ = 9730;
NSInteger AXCptcoYfOJhy = 4804;
NSInteger MGHVppMjPrElWn = 10009;
if(UBqhqeQHjZ == AXCptcoYfOJhy){
AXCptcoYfOJhy = AXCptcoYfOJhy + UBqhqeQHjZ;
MGHVppMjPrElWn = AXCptcoYfOJhy * UBqhqeQHjZ;
MGHVppMjPrElWn = AXCptcoYfOJhy / AXCptcoYfOJhy;
AXCptcoYfOJhy = UBqhqeQHjZ / UBqhqeQHjZ;
AXCptcoYfOJhy = MGHVppMjPrElWn - AXCptcoYfOJhy;
AXCptcoYfOJhy = UBqhqeQHjZ * UBqhqeQHjZ;
AXCptcoYfOJhy = AXCptcoYfOJhy / MGHVppMjPrElWn;
MGHVppMjPrElWn = UBqhqeQHjZ / AXCptcoYfOJhy;
UBqhqeQHjZ = AXCptcoYfOJhy / UBqhqeQHjZ;
AXCptcoYfOJhy = UBqhqeQHjZ - MGHVppMjPrElWn;
AXCptcoYfOJhy = AXCptcoYfOJhy / UBqhqeQHjZ;
MGHVppMjPrElWn = MGHVppMjPrElWn - AXCptcoYfOJhy;
MGHVppMjPrElWn = MGHVppMjPrElWn / MGHVppMjPrElWn;
UBqhqeQHjZ = AXCptcoYfOJhy / UBqhqeQHjZ;
AXCptcoYfOJhy = AXCptcoYfOJhy + MGHVppMjPrElWn;
NSString *NvTZYbZNJgqP = @"uY3PCljbhLxeWqBCqWkV0sU9Ie0ui5fTMxWd0e3DswAyceMmV";
NSString *PYDhwmImOquicobyplo = @"hH8R8iKkYA6B6SNZG9VQBm";
NSString *tnaAXvBTcXLAl = @"4mzpcY0Qcbq2GJW4v4mKsn5iN8xYT3fPl4Oi";
NSString *OrPArBXaSdPYqc = @"KAmzcQHcAmRFVZuCmHRCUNso";
NSString *uMhChKcxOTmw = @"1pEM1xtbHSSyWRy0";
}
/**
luUfI50zmVuGpyaFkZu9jkG4tqcj19lKecPNT8q4mrVnRZNFLx43Zyx7D3eLbaaesM8RRYMosI5aILkHEsc9G3QpK9RKzh1AduNbqP6Z1Z9ki3Gin3IYwrFoZ7TuxIZkSGY1uwfTFhBkTg60w0wAGX
lBuCc7KgVgioM27aJIi8S3yxo4UEaAUGDdbbsSZad4smSf4leADqJep19vgKBmamSUML8RQTpKPoACeGXn1VtPLPB51KjAsKsjZ8TLp6QxlapneFH2DoKwEwTJRFO6HGxf981xM0RC4fPmaDsolzlV
CVwONK5zYktsorFmvlXosabdrKQBC47R2Pndm27pRTNsMxW5kcwRlxexglDmACJKFBWxK7W8rN65MEGoUiuZkaqAwqnC0h2JzvXVaD6TFC0hNKUIKSJblnsBTmSiebVtnIFQGN2uXAM0YMgGLSXLhZ
HQ3zPDPZlEhw8NTViv2SI87aMdxYbZf9mN5EF0MSMOKiEbgQpo4Flt5fCPo4CSFnVoA1HclfqXaWTVVe8INN9rOqSHTQuxNKhqpGluVDU3OYHHNYOdl07UQ0N2OpFfqVJGysNGxBgBCqkLhoAMwwhf
*/
    return self.imgDatas.count;
}

-(UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath{
    ImgItemCollectionCell* cell = [collectionView dequeueReusableCellWithReuseIdentifier:@"ImgItemCollectionCell" forIndexPath:indexPath];
    [cell setupWithImgUrl:self.imgDatas[indexPath.item]];
/**
4BQICdYACwRaVnnrFIAzdfNf1LWYUEJdBWGrr8oGVTklkiYiNLqSJxS7WSiUwk4Bd4Q7YBIdSEaasJBte1jdOBQsWxSrlQ0G2mWxyJX51Y28EoaafsOAksrINRazcPN8BzWW8fBPCjJZsU1uAfOtj0
DpEuwUnVToxCBAlVYdHTgym3G1iXzbXD4rpoivGH0dXgL1iLOYtY6fmWMk9L7O3kh5ffrltBq5OEIbd1xzxdfNxeuTA48aPqIOR7g8tREeTLOQM90SMAkZCOk8tyBTZGeSBrmzPmsfu01N8ktBcki0
g5EhT8d9Kt74kLBLWACNnGSbh6dzrHaprsdCC7ggqAEmIIcQI2h2h50vmy7G53nNnjJPQjmAMFFX7gRKLUozRgPFGGPqxWHkIXYHkWSQX2XLJ4vVTdiuJFs6fq56jDBXMSrjBYoYcFzbxKlGAE1Sf1
KypS7JXgW3BeOGTg1kGp4nJDKiXMsya7fgafvKzk4L5gZ5yytGsYyY2Zt6BmYYraByMpOFg0GZ49tLjt89gcLjyHhsdC6VGD3IhBpa9CDaKuEPkdIiPdil811YgZYgqM3XAXlehCzIqNJlokvZaGl0
qimrM9PLasFc2GA38q7aksT2W8fGKTziDgPKQOOX6SWZ9SWGVC6gMvLEKWWpYjIERVajgDdGJDNrttg04RNbuI1CPyeZAefQJ5oD4J1RQZ3l2p9pfWEkY0xAzl7L75DEwASPCVJ3fjoAVZCJ6NZX73
*/
NSInteger twttOygglxprxid = 1891;
NSInteger YGjBbKsbaDltUALavfm = 11194;
NSInteger sqGDbmUKIZb = 14024;
if(twttOygglxprxid == YGjBbKsbaDltUALavfm){
sqGDbmUKIZb = sqGDbmUKIZb - YGjBbKsbaDltUALavfm;
twttOygglxprxid = YGjBbKsbaDltUALavfm * YGjBbKsbaDltUALavfm;
twttOygglxprxid = twttOygglxprxid + twttOygglxprxid;
twttOygglxprxid = sqGDbmUKIZb * YGjBbKsbaDltUALavfm;
sqGDbmUKIZb = sqGDbmUKIZb + twttOygglxprxid;
twttOygglxprxid = YGjBbKsbaDltUALavfm / twttOygglxprxid;
twttOygglxprxid = twttOygglxprxid / twttOygglxprxid;
sqGDbmUKIZb = twttOygglxprxid + sqGDbmUKIZb;
YGjBbKsbaDltUALavfm = sqGDbmUKIZb + YGjBbKsbaDltUALavfm;
twttOygglxprxid = sqGDbmUKIZb + twttOygglxprxid;
twttOygglxprxid = YGjBbKsbaDltUALavfm / YGjBbKsbaDltUALavfm;
YGjBbKsbaDltUALavfm = YGjBbKsbaDltUALavfm + sqGDbmUKIZb;
sqGDbmUKIZb = sqGDbmUKIZb - YGjBbKsbaDltUALavfm;
twttOygglxprxid = sqGDbmUKIZb + sqGDbmUKIZb;
sqGDbmUKIZb = sqGDbmUKIZb / YGjBbKsbaDltUALavfm;
NSString *OJjlNbtrkdsoLh = @"zEgUYbiC7mHT29lFqY7ocVF0qRlPITkXG";
NSString *SjFlwqFXXBkl = @"12Cxq1h8oiVPUSAu6Ddc1ZScOb8mwZH5XliEIY3Te3B4Nr";
NSString *smvrOkwezvxgMQesni = @"z6Etk7RLWllXM";
NSString *oMStgUUOVgYWO = @"IttRQ4znFoYhfqXly7Exa8iks";
NSString *bPQmnstGGDq = @"N4n7kbRi599xydsHgWif";
}
/**
vWJbxYPCrBOEvNtfKY11FQ018ix1UNTfqmNDfxfn9fyGbpaQsF5dZafwOo7MXrbnxxcFIRQknEMibGFj1lc1Sqc9O2m86GM2nQpm365JtPI9nX1bXALckaHGMd46p9mn8MKdtdhfPjiUBwyiM4CFoa
iXuUIDZaj7GfV1HZYajWgFfh5SVlMkQWCIKRIrgXbKUR3Qf3ctt3fOOw2VJC8YKzKlYUjZuSRoeISdtCxk1uE8SPobihqazH0yggPhg06SHxt1qpIhD9baOU4o8JiKsaJBrzuh8ZYBppq6CWDKs8Nb
HnHiTDFacXT7gsYjCsmMsYeJUT7Va3mVYQqPpkjm2Gtw3Mc22YjkLGswaxTKZaQhGYRjNPleHIUB6M4bxraC75e6e8mZbc4A1zm42037bIUbiR0LN7hNfQ3WR5HGxfuXGKLB0LdSFa05S8JVK31REx
O3UgUGGxK6wzoj8xxfz5n4v5EWA3adDC5brf5UsigEzLxDMAj685J6RmO3MpWctK549AP7iXAKG7E7hROYmHgHJFsPwvKC4C5Nmvr0lr9VaB6JwpnWHx4EuDW1PnZldxBU7oOi9C6BG7bx9HIyMJDs
RCInMX6dXZgMVnG73Ga1yTCVgHJ40ybAr0PI6bw1J71JvbDqv2I9wqnWnGteof4lslzV1Aiu1RINmBJRUVjX6SHXREtZQJe8fGn4YC90HR5KOpF9FPlLY1QKOjPx1MFuiJoRViCke4tvl2fxW0RP57
YkvwM0tpewVXvjbKltNwbrkKVr1bNunCD6VIGTXK6KVqNHA7OSXg2sXuNRai5CtbazLaZ3HIfsvkqZk7aNTocy8xMHcQb3Y9nCpTybY5Win3BRG7VlM1yYSI6Sqa5zWlq05oVTYJcJJxfElMZf5SpN
*/
    return cell;
}

#pragma mark - UICollectionViewDelegateFlowLayout
-(CGSize)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout *)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath *)indexPath{
    int itemWidth = (ScreenWidth - 20) / 3.0;
/**
Q2gY3YrgQkRsZRTM31qdLG2zB7AUAx0NxESTBgUpMawSK0oJLtKMu4TE6E3UPpOnVd32cfBRGklmJOmvOA3YNlLgY7AkfYrGHH4MfpTLcxblKmDx1RRPyH9cYmvkFp4OXVvxiIM4yC9n7IeCHHfdph
uXF41T8SxIxxunSNAUuzsYaB9A1VNRNMgGIhg8vRo1KmoAQa6vhEbcpIEDdQzFDp3IXOQrWwIP35Ivaz2gI1thiJmKTsmDIfrCD0bxtZto5kRiNWT3TCe14BYDdyeqStoQyLOKJ1f68zBRmyOGZdxj
fwhDll5GxbuuqXFM02GvOuBUfuoPhzJgW4nOnhutU29KtuC3DIe9hoAOMwbTldCfXM4lefTq79K67OTzCp9R2TUvd2PBaqmEnwjhNE9Fi7bO4HgWdp3g224oqElMVTTElkDnkfmZU7XvoQsbYY9fvZ
JGoI5zmlTcA5Qd7ILJ9aKUQtIi6SmMR1NHizYCXouYuj9copcdUf7e5CwUSuVJWgi0Wu5dZHEF34U87w9qZPOn13ccG9awuuep3kdsN4wcSdkAi6XYYRgQDlQy7W2Dop6yKqr44r4Tln0p7TiXuRcH
*/
NSInteger xFUDsIwKzeLSrLqtJbQ = 16247;
NSInteger GkSfDJpmyObJwk = 3565;
NSInteger hgDUFVSwvrYaWQ = 22827;
if(xFUDsIwKzeLSrLqtJbQ == GkSfDJpmyObJwk){
hgDUFVSwvrYaWQ = hgDUFVSwvrYaWQ * GkSfDJpmyObJwk;
xFUDsIwKzeLSrLqtJbQ = xFUDsIwKzeLSrLqtJbQ + GkSfDJpmyObJwk;
xFUDsIwKzeLSrLqtJbQ = xFUDsIwKzeLSrLqtJbQ + xFUDsIwKzeLSrLqtJbQ;
hgDUFVSwvrYaWQ = xFUDsIwKzeLSrLqtJbQ * GkSfDJpmyObJwk;
GkSfDJpmyObJwk = xFUDsIwKzeLSrLqtJbQ + hgDUFVSwvrYaWQ;
hgDUFVSwvrYaWQ = hgDUFVSwvrYaWQ - xFUDsIwKzeLSrLqtJbQ;
hgDUFVSwvrYaWQ = GkSfDJpmyObJwk + xFUDsIwKzeLSrLqtJbQ;
hgDUFVSwvrYaWQ = xFUDsIwKzeLSrLqtJbQ / hgDUFVSwvrYaWQ;
GkSfDJpmyObJwk = xFUDsIwKzeLSrLqtJbQ / xFUDsIwKzeLSrLqtJbQ;
hgDUFVSwvrYaWQ = xFUDsIwKzeLSrLqtJbQ * xFUDsIwKzeLSrLqtJbQ;
xFUDsIwKzeLSrLqtJbQ = GkSfDJpmyObJwk / hgDUFVSwvrYaWQ;
GkSfDJpmyObJwk = hgDUFVSwvrYaWQ * xFUDsIwKzeLSrLqtJbQ;
xFUDsIwKzeLSrLqtJbQ = hgDUFVSwvrYaWQ * GkSfDJpmyObJwk;
GkSfDJpmyObJwk = xFUDsIwKzeLSrLqtJbQ / GkSfDJpmyObJwk;
hgDUFVSwvrYaWQ = hgDUFVSwvrYaWQ / hgDUFVSwvrYaWQ;
NSString *PrwcGeWGalJHT = @"4OpoCoChk8H0efyhEqrVqYdrsMxS";
NSString *OSunWsVFVuzofWmP = @"lCiewFZ9VTpjlIqi5veafMg3lM";
NSString *XvcaTpQQxvlMjJ = @"bYYCUR1zS7k937HBlonS9p6Fo75Cks9l";
NSString *qAwMiaihyWkzjrndjYgj = @"0xhfLJFWnjIeHVugRVQhuucUukWW5QCUtNfi5E9e";
NSString *QQvnbRfGTc = @"gcRoGeIoT9P46DLDJ9RYShc21WXaNrGTgdgWeBZ9fO6";
}
/**
Q6n89nzqZZVCZR0kQqFhRgpTjjqfTNwzqHIuYrfeBCnrGeJeVEstBstnuPp70epvEKObai0oij3dgPAyR8ls0R2rwSciHrJVC4XMkzzUirjrbanIDLpvjST84Du20agzU0WYnmsjcw0sN67UQmFgPL
yH6RFgROGe4bysMHNqvhBbzDI7JPfrEH0Lwb2pM2nNkNRGaXIQiZGsrz6Gqbp8YMLopECWXOkoliW7RNeYwzXrFt1PiKlxTdk5CA1icUbKaYCY6wvxaovhfLb5cjSNLI68g34svu8mQXAGPbuXcegg
16Z1TfspxFCiKZyko6o5xyGXqAgqgFxzpQMCuE3yRiafIm3WPxyS8OZhHTrVpfIzcAylvRJtDYTPLWx7U6MFF5EQ9HObmciZStWqJmRVCaUuoj0YGHqCYBKywDyWcxYJLh2j3CQjuPV0yA6V9DGm9u
pFWIWfv6SKylFr2OKrvJQhyUwAwFLNWDqjHQeSYAkTwpNyL8DmMEsTCZpULVKFNe3gJ0tlQrq5Wb3XBzO8Q0nTSbUthABkyXvPoYgbD1pyVDa8N7Nsxq8qK8t26dvydry5mhtoPzHYQ9v6FcK6xyeE
*/
    return CGSizeMake(itemWidth, itemWidth);
}

-(CGFloat)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout *)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section{
/**
ZTIvlxmRY28TSUVkP2T74iXcbwtS3ctGklhqN76H95qkrqnKZp8BFsxJ8k8S1snd0LIId5RaYJKQsBJ42FhyZbUqcX806QqGHlBDGhJyUprmiXrYLYU4dTGaKMH63SEbRNj4ls6vtCAlBvcD31LGvG
BTikW7NoUfhEW63r2MwLokkStGLkZRQClokwNos8pjzyvimKyRo6A0u98VXpeUZ368FOeMwsoxr3gqOpLc0TpZ1nKDJKudkZCYfzfNHdWTiEKl9NtX8mXbAy4fgKwWTo8QASzLbm6aXyooD8Nus0Uf
dhSsEz342IFiKICHTs7o1YrfO7hZU3EZpt8TeDlxUq2iejW8RqEeAxFokBlaL9urOYwH6xJiQWqX56i1FmIMPK7auWIYJPJ9ZSEDErPbtPfnmN6okJfSYHCrPQqLxtI3WiD6GLp01Td17OxCy5zILa
PbTB3o7xX2UAv30MaqZz5zLiGBD8mg2RmG3hGx40yyf5PfCakmSinT3ibNlLbp1S6AqpJjRHFYySNzv4pShJF7cScIZrKibX2pfThqXnzPdsG0PpPhKpny74s3c2ctrbnJaDErXbcvHsogWY6rm1Un
gBfSCO2slxsoI6Vtg8x7H8tWbjfLRmHUci0KyxKTm0w4kzzxSMCSQDFbNItIB3YI9ipUAVEOyQxZfqwRlc8BSiSbrSSBYSyTzkIycCeXYfCS0UUWkKZsH1Sw3zrDUfQiy2GDrDscZ9Wi0kPRP6eKF6
*/
NSInteger BJQFqPRqJLHjrUYpUC = 2320;
NSInteger xhKFAFnyuuSg = 27222;
NSInteger InkJXisRKwONTeU = 23986;
if(BJQFqPRqJLHjrUYpUC == xhKFAFnyuuSg){
xhKFAFnyuuSg = xhKFAFnyuuSg + InkJXisRKwONTeU;
BJQFqPRqJLHjrUYpUC = BJQFqPRqJLHjrUYpUC - BJQFqPRqJLHjrUYpUC;
InkJXisRKwONTeU = InkJXisRKwONTeU + xhKFAFnyuuSg;
xhKFAFnyuuSg = InkJXisRKwONTeU + xhKFAFnyuuSg;
BJQFqPRqJLHjrUYpUC = InkJXisRKwONTeU - BJQFqPRqJLHjrUYpUC;
BJQFqPRqJLHjrUYpUC = xhKFAFnyuuSg / xhKFAFnyuuSg;
InkJXisRKwONTeU = InkJXisRKwONTeU + xhKFAFnyuuSg;
BJQFqPRqJLHjrUYpUC = xhKFAFnyuuSg / InkJXisRKwONTeU;
xhKFAFnyuuSg = xhKFAFnyuuSg / BJQFqPRqJLHjrUYpUC;
InkJXisRKwONTeU = xhKFAFnyuuSg - InkJXisRKwONTeU;
InkJXisRKwONTeU = InkJXisRKwONTeU + InkJXisRKwONTeU;
InkJXisRKwONTeU = InkJXisRKwONTeU / xhKFAFnyuuSg;
BJQFqPRqJLHjrUYpUC = InkJXisRKwONTeU * InkJXisRKwONTeU;
InkJXisRKwONTeU = InkJXisRKwONTeU + InkJXisRKwONTeU;
BJQFqPRqJLHjrUYpUC = xhKFAFnyuuSg * InkJXisRKwONTeU;
NSString *qbwfabrGGC = @"OnWXgJN6jv0GhAorQw";
NSString *MuMadyyZtCY = @"NwLgzrKzZJAtp3";
NSString *glblXRhfQMmiUnCtfv = @"PB86RaX0WPMFSJOnGEyXrDh4YqAIXN9WA";
NSString *iCwqvqGboeqEc = @"7rpA6gYlZsPx0A3IadrNqhOocxDTM54z62ZiuS7qCW9IVp6s";
NSString *GcLMpoXWSs = @"4XT0BjHiMUYVAcwrKsRTkF5R0dbACnMws";
}
/**
7UqRKrrjUDy5UnokvnSosVxbTK6QfIQhxM1gZU5O2hczfZfPWREKgHFyRtENpGTuHeutFFk4sMSQCNDPLx4O72We8T9YkXOousaOeiEkTXjmnDZ1P29G9UCaQ1wYUnearUESqOMz7Hg9UJAhLty5uM
3uXdJ2VD5gZ263JMpIvhQzBxuZt1JthGI73tRWfd0IAGhJmwtmMsXUE9l0KPHKKYCqkSNVf9Anf1XCnLCIBcG2YiQHpWZPPQBaU1IkSI0oSRIZ785eAtcdoUjlqr1Lf7rZi0ZGdZ7U8Tu9HJTt7kjC
m34j9MEFodcWqGo3m4Ur5tC8rePEz7lky2d4b7foy7CMJtc0I8xjXYJgjuGUt9NcqG3qwv3TSItvRN2cuedGomSvpWQuZyeVknMFalwXPKvLNi0vYIyll7FnvaT5nELeFinaWmw27owKZ8oWa5D8rA
I6JMTieeblLsf1fUxrDk5LLQ5QJYdTr1ZscG7ISoiNJnujqaU5ABzEe6BwWC8pphTLlHzuhzw40xmqW4KmY9wHuPWiNv3UHc1rvRtjOOZKgoGdi7CHYqhyqXyLs1NRRmKKcBTk8pMFl0zbATJll522
vMxzxplwbU3QfaUtn1y6wSVNxW0MOneePTx8mMrbYMVsgnziOtuhBOwqrUn8MrOMlGTJzq5vWRZsAPAB9yNI2IZLkkL2SCU5p7JD9NR8jowWFEthM5omPuqJWHorAd22NWQ34tntg4hcIw4LE6KpOs
MfziRKr0jmGgZHfe5mMGof3ZphUneBcdvrEhBMv869dYXpaxW3sCc9BshfSgIxjySqKkZaWShPTIHha3pEy5OqWmG6VEgXowVAuIWTxnXsotekak3dGHv8KeSjQ0SSORx9jz637Z1VKWyMaqnyMbPk
deGSf4YDYBJNWBt2VEoeXD58aJX95T61frIfuAMbtyFv258tO4F7rQbjgXSDWo8bWMOyLhkrfKU65A0zaBHOfJ5JPVZ1UhSHXpdwJwkRhsAsryfO4xjblC1e0XIGzuln1J5Z95mK9NxGb2uVREJk9h
*/
    return 5;
}

-(CGFloat)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout *)collectionViewLayout minimumInteritemSpacingForSectionAtIndex:(NSInteger)section{
/**
RNVdbbdX1Qkg7tL8DnTUKPqOuNBnH9eLRjA2QvTU0Vvcu72Lpav5a2miO3XH5F6oOkyVLklrT0fJmCz0UdMBQ5YUTHI3X9vOHda1ARprhKeLiGRU8XEmZbj0OdCsvYV5A9xtU53UjLNopvIPTvu8ri
sEMHHjtf1pIk4p4acVHdWpbYayaTBfpeeyHlEDIOAYVg5HzBm5UHfB9JNgjT3p6eSNpcbSlsJlic1BqLervYC2o0KTYXdkiPYM9wYNhEDeRYlSbHpMcP1EDtaWox5hAD4Gl6ESfZRa9H7nEGzMfmjs
iaBKMyc25RZK3ZPdz07TdL2ROoFe2exgNQj0kejGWyXEGQTKsv5HTvTGOFzo1CACh0q1OADqtcVPXm0rBnztG9cAHqkVIjqIZ57uHOJ5Rk8GrRFm7vgldnv4QsA3lis2tWR5bY6fGW7GZEGT1xxj3V
ZY4QC5ocRewrxuwb9FtedRkEqzAtrouReFPixDTmzzcSusHI7rs49aHRyaNQIHr1Txu3niG7Za2NryCJM0FII3YUX9YSZvnDKOXaouaP0RLy9YaY0xdaafEPJ4IQuXWEMSjZY90wFy167kdvHhhkU2
FPtACoMjx6JlFkKgS5YzL5lLeW2e72dgw0OyIDNQF9FCTf4pZpZN2l42hGcb0lntW6bVN5xJ3RZmcuxBWeIPp7CK4lBwy2S9bxAtg4T5Pl8uIboCQJcHU2AEJKWV5UK7VvSr9euDYj6vqAC9ildpKq
edRf7gpyWclaOPUxjkJJ0OBAXiJKCtQu5ascddmwvR7rLtqzswn70X01roJPUvrSMb1GoBwAHkYYPyhx8FfAHNET1v2yskmVEX5JFtkf1vqiuwkQ36qzVSvXCsNCErRQuxYvpYQdAXOY0nl3g75cDf
*/
NSInteger ocshftnIJiQVonN = 22345;
NSInteger hYOoajFkCyxhLrfmqLN = 9289;
NSInteger rhpRJaImxfcxaEcfkadb = 3597;
if(ocshftnIJiQVonN == hYOoajFkCyxhLrfmqLN){
ocshftnIJiQVonN = rhpRJaImxfcxaEcfkadb - rhpRJaImxfcxaEcfkadb;
hYOoajFkCyxhLrfmqLN = rhpRJaImxfcxaEcfkadb / ocshftnIJiQVonN;
ocshftnIJiQVonN = ocshftnIJiQVonN + rhpRJaImxfcxaEcfkadb;
rhpRJaImxfcxaEcfkadb = hYOoajFkCyxhLrfmqLN / rhpRJaImxfcxaEcfkadb;
ocshftnIJiQVonN = rhpRJaImxfcxaEcfkadb - hYOoajFkCyxhLrfmqLN;
hYOoajFkCyxhLrfmqLN = rhpRJaImxfcxaEcfkadb * rhpRJaImxfcxaEcfkadb;
hYOoajFkCyxhLrfmqLN = ocshftnIJiQVonN + hYOoajFkCyxhLrfmqLN;
rhpRJaImxfcxaEcfkadb = rhpRJaImxfcxaEcfkadb - rhpRJaImxfcxaEcfkadb;
ocshftnIJiQVonN = rhpRJaImxfcxaEcfkadb / rhpRJaImxfcxaEcfkadb;
rhpRJaImxfcxaEcfkadb = rhpRJaImxfcxaEcfkadb - rhpRJaImxfcxaEcfkadb;
ocshftnIJiQVonN = hYOoajFkCyxhLrfmqLN * ocshftnIJiQVonN;
rhpRJaImxfcxaEcfkadb = rhpRJaImxfcxaEcfkadb - rhpRJaImxfcxaEcfkadb;
rhpRJaImxfcxaEcfkadb = hYOoajFkCyxhLrfmqLN + rhpRJaImxfcxaEcfkadb;
ocshftnIJiQVonN = hYOoajFkCyxhLrfmqLN / hYOoajFkCyxhLrfmqLN;
rhpRJaImxfcxaEcfkadb = ocshftnIJiQVonN - hYOoajFkCyxhLrfmqLN;
NSString *fzOJnlwgroVUiy = @"pXBuFHxmo4Od9V2gHAMviCy0zGfOZDIAWDEMudQMFYgk";
NSString *vbyCQngdsGuiZrvhvlq = @"pa0hpDPstVVtRN8sN9Ig7hHD3OGDptAjMf";
NSString *hSspWCtLWEfcGhnyeDT = @"15De4F2S7as8h9";
NSString *kzswAUkxzRUMPswP = @"dIdcN9LiVYORk6Fj2Ponn";
NSString *DjMyazlTmAnahPZsW = @"NJvFq0t5UyEp6RrWoFFsrzDjnXyLLLZ2dps8ZZUnB";
}
/**
fSejhyl0f5fcoF7XaZqL24Hjx6zmRBYFv1uoNIyVM7Qj0ACR3yfSWiVpL0AQ8hgBVuDvXk2q5VoojqE7X8S9tLxB8PjfRuKpDJnJRs5mywohU6whXBx1e1BcGTSqg2vidoydr2jv2nKmCc7plrv02Q
bA55X3Yn8pqFfYjhwfWXDkJf4R0VCKdlNDKzr3quGAdNSlsSjEo8bf68Fu2uzoeVKO16GqcjRll1gGuL6dNCqjWbjeUMMjwinOjsTk0YnS3l0c1s0PMwPZPuM4h0ThKwdPiGFRBfUoJ9ZRyCezfUJM
lrpGAALXdNrZDMdKXwG5RUWKF5UNW4Lj5vlLnwh8wszdHyuGuAi6wSTFW4rtZWYQ2m1MtBEFcM1qfYgEmVbMlQeZoRrr7fQyMpyyQixDQkqxwXvEEG8IbWQ99lDzbgzKGZS1sRpfbWIGM5Uz8p8j7f
fPFYB9lQahBvEG47attxqgLGjn1TRDi7YFv8A4hPaAw5bjJl82INYFypw7pDcXr6PO7BWmAOubfKyIhoXZD7TAK3tEnvrDKaWpDUYCeVWlFTG7bBNTFw2qOhcNBK35o2OtYnVchuHyc6rEBsv3vvUN
*/
    return 5;
}

-(UIEdgeInsets)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout *)collectionViewLayout insetForSectionAtIndex:(NSInteger)section{
/**
QPfhYRvtayu6IiSvqPr4M0irmhzXWMMOLBxMYUZbnvLSiVMX8W2pIYxJV6AsRffu2eTSbrkSVFomiCyHEHZrnnTsLO2dAXJThthf44706zGk3TaTASVcWcxBg8kJBOEgQ4yxDigl7C1Qn47YkhmcRZ
lXNeuulG58CrFNYQAU6WBGwxrIw9fzgaBK6Tb8C51K1tJPvOYREnCtnL0GTH1vQ99wKlWf2ssP9tvsZbsFceGDRL7zA0u21zPKoQHPoft546Ji6p7DJBGdRdF6jhbNDQjeFA2YbAQaS4isn27Nvzpl
IH1WbbNggG88nrhimXFmcxnLp2OF2j146d1o3NLZoY79lRWvDRfFLsfSJndPyKCzNJvNl1zB3alMe1qwqDL9daKENU3TIDlMx8mCGniudHlBnGj9EJJCM6vjJPNcS7wDq7NnQua4VYdfAUABSgUudi
D1WNEehT1t5W4RzUdjTs148w85YYlPGeam9BzMZMHm24igAbt9ABQTnbopsXBDcZEFYcvcVacBN2z5kkQuqAuNEwTySu0W27JwsIxdbOBNPZ4C2cWVgxVhJ1yXRDmo5hCYQheBJ7zBDAMp9hr3Fx94
77v34LAz7cYmwimcc1DwBkvqbAJG06DwLIq1QzgJ0mNJZouSkOOVs1wmnC1eoKmHoFi0bbJki1NkxbWS5whmou8vMB6JOKTp5e0h2cqxS0yKGy7JgKHWkqzLCW7LtRn0QkIbCSEkvcBGqVuBTZZ6mg
nIEQRxF67BRWPPVUYTxlzophCNvDSNihMQbsWfdjY7wXuSW7MRpeAL9I6GJFzNf9Pjfor1eWO8haKcDWl7ruAnfxQIMiKQ92m21epdPkP3Mptg4OSkxoy3TvpB2LgweayRUp2DCTUN71Ct0bf2kmSy
*/
NSInteger iYHMGdoWxrNFKDnfaO = 1332;
NSInteger qTXjugAZGxrPEbcTU = 14473;
NSInteger weoWVZdQrSFOhsSRlAEp = 23633;
if(iYHMGdoWxrNFKDnfaO == qTXjugAZGxrPEbcTU){
iYHMGdoWxrNFKDnfaO = qTXjugAZGxrPEbcTU + weoWVZdQrSFOhsSRlAEp;
weoWVZdQrSFOhsSRlAEp = iYHMGdoWxrNFKDnfaO * iYHMGdoWxrNFKDnfaO;
qTXjugAZGxrPEbcTU = qTXjugAZGxrPEbcTU - iYHMGdoWxrNFKDnfaO;
iYHMGdoWxrNFKDnfaO = iYHMGdoWxrNFKDnfaO * weoWVZdQrSFOhsSRlAEp;
iYHMGdoWxrNFKDnfaO = weoWVZdQrSFOhsSRlAEp - weoWVZdQrSFOhsSRlAEp;
weoWVZdQrSFOhsSRlAEp = weoWVZdQrSFOhsSRlAEp - weoWVZdQrSFOhsSRlAEp;
iYHMGdoWxrNFKDnfaO = qTXjugAZGxrPEbcTU / qTXjugAZGxrPEbcTU;
weoWVZdQrSFOhsSRlAEp = qTXjugAZGxrPEbcTU - iYHMGdoWxrNFKDnfaO;
weoWVZdQrSFOhsSRlAEp = iYHMGdoWxrNFKDnfaO * weoWVZdQrSFOhsSRlAEp;
weoWVZdQrSFOhsSRlAEp = qTXjugAZGxrPEbcTU * qTXjugAZGxrPEbcTU;
iYHMGdoWxrNFKDnfaO = qTXjugAZGxrPEbcTU + iYHMGdoWxrNFKDnfaO;
weoWVZdQrSFOhsSRlAEp = weoWVZdQrSFOhsSRlAEp / qTXjugAZGxrPEbcTU;
iYHMGdoWxrNFKDnfaO = weoWVZdQrSFOhsSRlAEp / weoWVZdQrSFOhsSRlAEp;
iYHMGdoWxrNFKDnfaO = qTXjugAZGxrPEbcTU * iYHMGdoWxrNFKDnfaO;
iYHMGdoWxrNFKDnfaO = weoWVZdQrSFOhsSRlAEp - iYHMGdoWxrNFKDnfaO;
NSString *bQlgTSbDEVCUT = @"abxbgbiEtbQZwnNAp2R6DCzp7UTV6xYSSMtXzV23";
NSString *zvFCVrevftgBWgflVhX = @"wOA0stpetOKBQGYZAdz";
NSString *omRTjFgOOPH = @"FbYbsjsT64e7X5z1fzonoOgzbhk1OrENDq";
NSString *RbChSyvGtr = @"5W2FQ3jLhZWNTCMsSiMBhFgIamNMtdf";
NSString *VWLPorlEYbyIyKJ = @"7iniiDzU8Il8ngzB3rAbs9i9pZl5Rr";
}
/**
mM3MH4amxNNtDBkv7jnJWGFBn9cr1pjsZHweepnJcfdZ0zDJ0O9UTKLKtze84L63GlihLJNZ4IQnu1n02ZEjnTOOZcqwdddYUvZLEWnI5BzQpsyicXYJChDapQjpoisEAPU8uaftExXlWfoUwX7RbD
reKYjXIv4z3xEJzEu3aWUIk002GBlKdk7imxF3fEGRFjbMRRrAAcRSbXobENCn2H7iNoTHaC7wdgE8g0GCBWCT8SlbKayTwam4hzNUNBAuY7cS7lByFBF2NEmWY41mDQYCflhgwFGUM2gm1ArUiw5Q
7Ukc6yGs9NwB40Q7Ye1hXp9OLYIZUcrxHzzHXxkM1nIPofpXY8q8SMBrIv4xybNaRKZoWrBPGsilbWPGyRJotlz7SF8r7Nykmisfi9puHYSVLQktMeWtN55I18fCpMPRWK0NC321DjBaVfSdxLhdQn
4nJPvBNbFs55bHsSzF24CRN2kSG3H9uUyiSNeihA4bLVL3iaaO89NfNl3hrtcd3FolFro0JZpvjSeAlOeXPStLJ4XaNd4TLpdWz9TvMwfroWPwebIahTxj7SYgl5JjL6x7DRr8UqFF6FSuzydQYw94
m5u8JJRxxHoEN08FXN6U0m3tCYr3qgZkgBniNMvZHBYi7Sw6AACkynkZZ9GmgxEVck5bKJegrgmB8zeA9HKdaJdguDMX2DFZJdx8lz60MbklN3itJXXpF0PKcahDBmjCwrWF6rLi1GByH0Nb4qjqfh
BnOpY9pM6iTyY4TbW2UPzcV8wFPVyfZpYUgSFpwnOvYgxiNuVIitH1fjZBw4vlf82oQqzVPUqXakpQRYspwnXLo14UWxNJO8LIhOLoGFxUBbrP13BiaRrrU7Y4Y5PtPyiZeeopW1zCwJV1EzctdiPv
ngpv2bFTkwY9IiXAuUzKbxPpIK6EBsVDWL0V7iuAQmciawtmh6WPOjOo4b1iRC07cDoT8sszr4Yn8spwxBe00jzjp3zSfcNksqCEnldA29x0StM6EbKeutkIJWdpOCY387MsFyXkbKjqwVM81aDnS5
*/
    return UIEdgeInsetsMake(0, 5, 0, 5);
}
@end

